name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: ["self-hosted"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.1.9
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.1.9'
    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec | tee BUILDOUT
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        GEM_FILE=`grep File BUILDOUT | awk '{print $2}'`
        curl -i -X POST -H "Content-Type: multipart/form-data" -F "file=@$GEM_FILE" ${{vars.GEM_SERVER_URL}}

      env:
        OWNER: ${{ github.repository_owner }}
        GEM_HOST_API_KEY: "Bearer ${{secrets.CCH_GITHUB_PUBLIC_BOT_TOKEN}}"
  
